font_family Maple Mono NF CN
font_size 14.0
background_opacity 0.8
hide_window_decorations yes

map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down
map shift+enter send_text all \e\r
