distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 5.1.12
install_time: "Tue Dec 30 11:38:10 2025"
installation_id: "d1a9ec50-4e5c-49b3-86a0-6e109986bc7c"
rime_version: 1.14.0