var:
  last_build_time: 1767145454
  option:
    ascii_punct: true
    emoji: true
    simplification: true
    zh_hant: true
  previously_selected_schema: rime_frost_double_pinyin_flypy
  schema_access_time:
    bopomofo: 1767071940
    luna_pinyin: 1767072077
    luna_pinyin_fluency: 1767072613
    rime_frost_double_pinyin_flypy: 1767150405