[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod selected files"

[[mgr.prepend_keymap]]
on = ["g", "n"]
run = 'shell --orphan -- "$HOME/Project/archPostInstall/scripts/launchers/yazi-open-nautilus.sh" %h'
desc = "Open current location in GNOME Files"
